# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd81bbbf2f3c9cb77f5887b497a9b912d7b3ee569b190518e65037ac404b7be6d4222fc4ace91eb9c4843ebba57f3b4cea33365fd3a9d6ae8b59cfdc3f75f2b8

test:
  secret_key_base: 7ef5975ac5b6c91a58e0ede40eed1c51f58c99aad9816b0be015c012dd73d112ba207c562683c39a1e13df764e5c7d649d3cd984038c705561c869135fb697c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
